language: cpp

git:
  depth: 5
  quiet: true

cache:
  apt: true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
          update:
            - true
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" COMPILER="gcc"

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
          update:
            - true
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" COMPILER="gcc"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - libc++-dev
            - libc++abi-dev
            - libstdc++-6-dev
            - ninja-build
          update:
            - true
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" COMPILER="clang"

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - ninja-build
          update:
            - true
      env: MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" COMPILER="clang"

    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          packages:
            - ninja
          update:
            - true
      env: MATRIX_EVAL="CC=clang && CXX=clang++" COMPILER="clang"

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - ninja
          update:
            - true
      env: MATRIX_EVAL="CC=clang && CXX=clang++" COMPILER="clang"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - python BuildAll.py ninja $COMPILER x64 Release
  - ./Build/ninja-$COMPILER-$TRAVIS_OS_NAME-x64-Release/Bin/ShaderConductorTest
